version = 1
SPDX-PackageName = "btp-cloud-transport-management"
SPDX-PackageSupplier = "Anke Ravalitera (anke.ravalitera@sap.com)"
SPDX-PackageDownloadLocation = "https://github.com/sap-docs/btp-cloud-transport-management"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and SAP-docs/btp-cloud-transport-management contributors"
SPDX-License-Identifier = "CC-BY-4.0"
